apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "sample-app.fullname" . }}-backup
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/component: backup
            app.kubernetes.io/part-of: kubequest
        spec:
          containers:
            - name: mysql-backup
              image: mysql:8.0
              command:
                - /bin/bash
                - -c
                - |
                  echo "Backup $(date)"
                  mysqldump \
                    -h $DB_HOST \
                    -u $DB_USERNAME \
                    -p$DB_PASSWORD \
                    --single-transaction \
                    $DB_DATABASE \
                    > /backup/dump-$(date +%Y%m%d-%H%M%S).sql
                  echo "OK : $(ls -lh /backup/)"
                  find /backup -name "*.sql" -mtime +7 -delete
              env:
                - name: DB_HOST
                  valueFrom:
                    secretKeyRef:
                      name: sample-app-secrets
                      key: DB_HOST
                - name: DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: sample-app-secrets
                      key: DB_USERNAME
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: sample-app-secrets
                      key: DB_PASSWORD
                - name: DB_DATABASE
                  value: app_database
              resources:
                requests:
                  cpu: 20m
                  memory: 32Mi
                limits:
                  cpu: 100m
                  memory: 128Mi
              volumeMounts:
                - name: backup
                  mountPath: /backup
          restartPolicy: OnFailure
          volumes:
            - name: backup
              emptyDir: {}
