apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sample-app.fullname" . }}-mysql-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  root-password: {{ .Values.mysql.rootPassword | default "RootStrongPass456!" | quote }}
  user-password: {{ .Values.mysql.password | default "StrongPass123!" | quote }}
