apiVersion: v2
name: sample-app
description: Laravel 10 + MySQL 8 - KubeQuest Epitech
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: mysql
    version: "14.0.3"
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
