image:
  repository: ghcr.io/amezianechayer/sample-app
  tag: "v1.0.0"
  pullPolicy: IfNotPresent
replicaCount: 2
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: "nginx"
  host: app.kubequest.local
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 512Mi
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - sample-app
        topologyKey: kubernetes.io/hostname
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
livenessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 120
  periodSeconds: 15
  failureThreshold: 5
readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 120
  periodSeconds: 10
  failureThreshold: 5
config:
  APP_ENV: production
  APP_DEBUG: "false"
  DB_CONNECTION: mysql
  DB_PORT: "3306"
  DB_DATABASE: app_database
mysql:
  enabled: false
